name: website
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Flutter first-party
  cupertino_icons: ^1.0.8

  # Tredjeparts-paket
  lottie: ^3.1.0
  timeline_tile: ^2.0.0
  syncfusion_flutter_pdfviewer: ^30.1.39
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/link_animation.json
    - assets/animations/planet_animation.json
    - assets/animations/cloud_animation.json
    - assets/icons/LI-In-Bug.png
    - assets/icons/Gmail_icon.png
    - assets/icons/github-mark.png
    - assets/icons/github-mark-white.png
    - assets/cv/Axel Olsson CV.pdf
    - assets/cv/1.png
    - assets/cv/2.png
    - assets/cv/profil_bild.png

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-BoldItalic.ttf
          weight: 700
          style: italic
